CREATE TABLE PET_CARE_LOG ( 
LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
PRODUCT_ID NUMBER, 
UPDATED_BY_USER VARCHAR2(30),
LOG_TEXT VARCHAR2(500), 
UPDATE_DATE DATE );

CREATE OR REPLACE TRIGGER trg_pet_log_insert
BEFORE INSERT ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    :NEW.UPDATE_DATE := SYSDATE;
    :NEW.UPDATED_BY_USER := USER;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Unexpected error inserting pet care log');
END;
/

CREATE OR REPLACE TRIGGER trg_pet_log_update
BEFORE UPDATE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != :OLD.UPDATED_BY_USER THEN
        RAISE_APPLICATION_ERROR(-20002, 'You can only update your own records');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_pet_log_delete
BEFORE DELETE ON PET_CARE_LOG
FOR EACH ROW
BEGIN
    IF USER != 'JOEMANAGER' THEN
        RAISE_APPLICATION_ERROR(-20003, 'Only manager can delete records');
    END IF;
END;